version: 0.2

phases:
  install:
    commands:


  pre_build:
    commands:

  build:
    commands:
      - echo Maven Build ...
      - mvn package
  post_build:
    commands:

       
artifacts:
     files:
       - target/sqs1-1.0.0.jar